name: Build and deploy to Server

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest1

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest1
            docker stop api-gateway || true
            docker rm api-gateway || true
            docker run -d --name api-gateway -p 30000:8080 -p 30001:5001 --env-file /home/api-gateway/.env ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest1                                  
